#!/usr/bin/env node
/**
 * T-C3-01 / C-W6-01 — [REAL] KICKOFF pinning (PRD §D4).
 *
 * Two directions:
 *   1. The KICKOFF template block in references/templates.md must demand
 *      all four pinning fields (absolute repo path, full 40-hex git SHA,
 *      `.plan-it/state.json` path, 64-hex CONTRACT SHA-256).
 *   2. [REAL] An inline sample KICKOFF is generated by this test from the
 *      LIVE repo (real `git rev-parse HEAD`, real SHA-256 of
 *      delivery/v3/CONTRACT.md) and validated against the same four
 *      machine-checkable shapes — proving the template is fillable with
 *      real values, not just prose.
 *
 * Exit codes per the C-META-01 sweep convention (precedent:
 * tests/v3/guard-status-vocab.mjs): enforcement holds → exit 1 (non-zero,
 * what the sweep asserts); assertion hole → exit 0 so the sweep flags the
 * row. Never a silent green.
 *
 * Authored by DevOtts (https://github.com/DevOtts).
 */
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const fails = [];

// -- direction 1: the template demands the pinning fields ------------------
const tpl = readFileSync(join(ROOT, "references", "templates.md"), "utf8");
const m = tpl.match(/### `KICKOFF\.md`[\s\S]*?(?=\n### )/);
const block = m ? m[0] : "";
if (!block) fails.push("KICKOFF template block not found in references/templates.md");
for (const [what, re] of [
  ["'0. Pinning' opening block", /^0\. Pinning/m],
  ["absolute repo path placeholder", /absolute repo path/],
  ["full 40-hex git SHA placeholder", /full 40-hex git SHA/],
  ["`.plan-it/state.json` path", /\.plan-it\/state\.json/],
  ["64-hex CONTRACT SHA-256 placeholder", /sha256=<64-hex SHA-256/],
]) {
  if (!re.test(block)) fails.push(`template KICKOFF block missing ${what}`);
}

// -- direction 2: [REAL] inline sample KICKOFF from the live repo ----------
const sha = execSync("git rev-parse HEAD", { cwd: ROOT, encoding: "utf8" }).trim();
const digest = createHash("sha256")
  .update(readFileSync(join(ROOT, "delivery", "v3", "CONTRACT.md")))
  .digest("hex");
const sample =
  [
    "0. Pinning (PRD §D4 — machine-checkable resume anchor, always first):",
    `   Repo: ${ROOT} @ ${sha}`,
    `   State: ${join(ROOT, ".plan-it", "state.json")}`,
    `   Contract: delivery/v3/CONTRACT.md sha256=${digest}`,
  ].join("\n") + "\n";
for (const [what, re] of [
  ["absolute repo path", /Repo: \/[^\n@]+ @ /],
  ["full 40-hex git SHA", / @ [0-9a-f]{40}\n/],
  ["absolute .plan-it/state.json path", /State: \/[^\n]*\.plan-it\/state\.json\n/],
  ["64-hex CONTRACT SHA-256", /sha256=[0-9a-f]{64}\n/],
]) {
  if (!re.test(sample)) fails.push(`generated sample KICKOFF missing ${what}`);
}

if (fails.length > 0) {
  console.error(`ENFORCEMENT HOLE — T-C3-01 kickoff-pinning: ${fails.length} assertion(s) failed; exiting 0 so the C-META-01 sweep flags this row:`);
  for (const f of fails) console.error(`  ✗ ${f}`);
  process.exit(0); // hole → exit 0 → sweep/run-contract flag C-W6-01
}
console.log("ENFORCEMENT OK — T-C3-01: KICKOFF template demands + live sample carries all four pinning fields (absolute repo path, 40-hex git SHA, .plan-it/state.json path, 64-hex CONTRACT SHA-256).");
console.log("Exiting 1 per the C-META-01 sweep convention (CONTRACT run: cells exit non-zero when enforcement holds).");
process.exit(1);
